### ISSUE TITLE
Add 7tv support

### ISSUE THREAD

**Issue by DatGuy1** [TETYYS/MessageHeightTwitch#10]
Unlike FFZ and even more so than BTTV, 7tv allows large resolutions on its emotes which is a big perpetrator in message height violations

**Comment by TETYYS** [comment]
I won't be analyzing how they behave with emojis/text/emotes near them, but I can add them with same handling as FFZ has if that's ok

**Comment by TETYYS** [comment]
Added https://github.com/TETYYS/MessageHeightTwitch/commit/cb470d122bcce03ec3229a88acba7f9d232b6772 , please test. It's not accurate, but its at least something.

**Comment by DatGuy1** [comment]
Yes, works. Is there any particular reason it defaults to off? Does it break if run on channels without 7tv?

**Comment by TETYYS** [comment]
Original constructor/`InitChannel` was left due to backwards compatibility reasons; I've added catches on initialization so that it doesn't break

**Comment by DatGuy1** [comment]
Thanks!
